name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validation
      id: validation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Validation
        setup-command: ''
        command: python3 test_agent.py
        timeout: 1
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VALIDATION_RESULTS: "${{steps.validation.outputs.result}}"
      with:
        runners: validation
